spring.application.name=dev-diaries-backend
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/devdiaries

# JWT Configuration
app.jwtSecret=devdiariesSecretKeyMakeThisEnvironmentVariableInProduction
app.jwtExpirationMs=86400000

# CORS Configuration
cors.allowed-origins=http://localhost:4200,https://localhost:8080

# Logging
logging.level.root=INFO
logging.level.com.devdiaries=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
